/**
 * Crypto Data Service — Ingests Polymarket Crypto events, Binance 1-minute orderflow, and Deribit Implied Volatility
 */

const GAMMA_API = 'https://gamma-api.polymarket.com';
const CLOB_API = 'https://clob.polymarket.com';
const BINANCE_API = 'https://api.binance.com/api/v3';
const DERIBIT_API = 'https://www.deribit.com/api/v2';

/** Fetch current prices from Polymarket CLOB */
export async function getCryptoMarketPrices(tokenIds) {
  const results = await Promise.allSettled(
    tokenIds.map(async (tokenId) => {
      try {
        const res = await fetch(`${CLOB_API}/price?token_id=${tokenId}&side=buy`);
        if (!res.ok) return null;
        const data = await res.json();
        return parseFloat(data.price) || null;
      } catch {
        return null;
      }
    })
  );
  return results.map(r => r.status === 'fulfilled' ? r.value : null);
}

/** Fetch active Bitcoin markets on Polymarket */
export async function getBitcoinMarkets() {
  console.log('[CRYPTO] Scanning Polymarket for Bitcoin events...');
  try {
    // Only fetch likely crypto events by searching for the "5M" explicit tag (102892)
    // This allows the API to bypass massive multi-year bets and serve the high-frequency markets
    const res = await fetch(`${GAMMA_API}/events?limit=100&active=true&closed=false&tag_id=102892`);
    if (!res.ok) return [];
    const events = await res.json();

    // Filter strictly to Bitcoin 5m/15m up/down markets using specific timestamp Regex
    // High frequency crypto markets typically have titles like "Bitcoin goes up at 12:15 PM ET?"
    const timeRegex = /\b\d{1,2}:\d{2}\s*(?:AM|PM)?\s*ET\b/i;
    
    const btcEvents = events.filter(e => {
      // Fallback to market question if root title is missing (which happens on autogenerated 5M markets)
      const primaryText = e.title || (e.markets && e.markets[0] && e.markets[0].question) || '';
      if (!primaryText) return false;
      
      const textLower = primaryText.toLowerCase();
      
      const isBitcoin = textLower.includes('bitcoin') || textLower.includes('btc');
      const hasTimeResolution = timeRegex.test(primaryText) || (e.markets && e.markets.some(m => timeRegex.test(m.question)));
      const hasActiveMarkets = e.markets && e.markets.some(m => !m.closed);
      
      return isBitcoin && hasTimeResolution && hasActiveMarkets;
    });

    const markets = [];
    const tokenIds = [];

    for (const e of btcEvents) {
      for (const m of e.markets) {
        if (m.closed) continue;
        const clobTokenIds = safeJSON(m.clobTokenIds, []);
        if (clobTokenIds.length > 0) {
          const yesTokenId = clobTokenIds[0];
          tokenIds.push(yesTokenId);
          markets.push({
            eventId: e.id,
            eventSlug: e.slug || m.slug,
            title: e.title || m.question,
            question: m.question,
            groupItemTitle: m.groupItemTitle,
            tokenId: yesTokenId,
            endDate: m.endDate || e.endDate,
            polymarketUrl: `https://polymarket.com/event/${e.slug}`,
            volume: parseFloat(m.volumeNum || 0),
          });
        }
      }
    }

    // Filter out stuck/abandoned historical markets. Only keep markets ending 
    // strictly in the future (cut them exactly at expiry).
    const now = new Date();
    let validMarkets = markets.filter(m => new Date(m.endDate) > now);

    // Sort by End Date (soonest first)
    validMarkets.sort((a, b) => new Date(a.endDate) - new Date(b.endDate));

    // The user requested only the active one and 5 future ones max (6 total)
    validMarkets = validMarkets.slice(0, 6);

    // Attach Live Prices (only for the filtered slice to save network burst)
    const filteredTokenIds = validMarkets.map(m => m.tokenId);
    const prices = await getCryptoMarketPrices(filteredTokenIds);
    validMarkets.forEach((m, i) => m.price = prices[i] || 0.50);

    return validMarkets;
  } catch (e) {
    console.error('[CRYPTO] Failed to fetch Bitcoin markets:', e);
    return [];
  }
}

/** Fetch 1-min Binance K-lines for Feature Generation */
export async function getBinanceKlines(symbol = 'BTCUSDT', interval = '1m', limit = 100) {
  const url = `${BINANCE_API}/klines?symbol=${symbol}&interval=${interval}&limit=${limit}`;
  try {
    const res = await fetch(url);
    if (!res.ok) return [];
    const rawData = await res.json();
    return rawData.map(d => ({
      time: new Date(d[0]).toISOString(),
      open: parseFloat(d[1]),
      high: parseFloat(d[2]),
      low: parseFloat(d[3]),
      close: parseFloat(d[4]),
      volume: parseFloat(d[5])
    }));
  } catch (e) {
    return [];
  }
}

/** Fetch Deribit BTC-DVOL index */
export async function getDvol() {
  const url = `${DERIBIT_API}/public/get_volatility_index_data?currency=BTC&resolution=1D`;
  try {
    const res = await fetch(url);
    if (!res.ok) return { value: 50.0, percentile: 50 };
    const body = await res.json();
    const data = body.result?.data;
    
    if (data && data.length > 0) {
      // Data = [timestamp, open, high, low, close]
      const closes = data.map(d => parseFloat(d[4]));
      const current = closes[closes.length - 1];
      
      // Calculate a rough rank percentile against the last 30 periods
      const lookback = closes.slice(Math.max(closes.length - 30, 0));
      const below = lookback.filter(v => v < current).length;
      const pct = (below / lookback.length) * 100;

      return {
        value: current,
        percentile: parseInt(pct),
      };
    }
  } catch (e) { }
  return { value: 50.0, percentile: 50 }; // Safe Fallback
}

function safeJSON(val, fallback) {
  if (Array.isArray(val)) return val;
  try { return JSON.parse(val); } catch { return fallback; }
}
